### ISSUE TITLE
NO DOWNLOAD!

### ISSUE THREAD

**Issue by BRUHLETMEDOWNLOADUREXEFILE** [Cvolton/AeroShotCRE#5]
GIVE ME THE DOWNLOAD YOU LITTLE TWERK! IF DONT SEND ME THAT DOWNLOAD LINK, YOU WILL BE REMOVED ON GITHUB BECAUSE ITS IMPOSSIBLE TO DOWNLOAD IT FROM THE MICROSOFT STORE! I DONT EVEN LIKE THE MICROSOFT STORE! MICROSOFT STORE IS BS!

**Comment by KLanausse** [comment]
The hell? Dude it's right there in the releases tab. https://github.com/Cvolton/AeroShotCRE/releases

**Comment by Cvolton** [comment]
skill issue

**Comment by Cvolton** [comment]
the reason some versions are Microsoft Store only is that they only fix bugs that affect that version in the first place, however 1.9.5 is currently the latest on both Microsoft Store and in the standalone releases, so I have no idea what you're even asking about
